config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :matches, only: [:index, :create]
    end
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  # Include default devise modules. Others available are:
  belongs_to :user
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :matches
  
  has_many :users, through: :matches
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :username, uniqueness: {
     message: "An account already exists for that username!"
   }

   validates :email, presence: true
   validates :email, email: true
   validates :email, uniqueness: {
     message: "An account already exists for that email address!"
   }
   has_many :matches
   has_many :pokemons, through: :matches
end

app/controllers/api/v1/matches_controller.rb
class Api::V1::MatchesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def create
    pokemon = Pokemon.create!(
      name: params[:name],
      weight: params[:weight],
      image_url: params[:image_url]
    )
    match = Match.new(pokemon: pokemon, user: current_user)

    if match.save
      render json: match
    else
      render_object_errors(match)
    end
  end

  def render_object_errors(object)
    render json: { errors: object.errors.full_messages }, status: :unprocessable_entity
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @matches = @user.pokemons
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.email = params[:user][:email]
    @user.avatar_url = params[:user][:avatar_url]

    if @user.save
      flash[:notice] = 'Success! Your profile has been updated.'
      redirect_to @user
    else
      @user.email = params[:user][:email]
      @user.avatar_url = params[:user][:avatar_url]
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <% if current_user %>
    <div id="signed_in">
      <h1>Like Me?</h1>
      <div id="app">
      </div>
    </div>
  <% else %>
    <div id ="landing_page">
      <h1>A World Beckons...</h1>
      <img src="https://pldh.net/media/pokemon/ken_sugimori/20th_anniversary/151.png" />
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title>Mew Meets You</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div data-sticky-container>
      <div class="sticky" data-sticky data-options="anchor: page; marginTop: 0; stickyOn: small;">
        <div class="top-bar">
          <div class="top-bar-left">
            <ul class="menu">
              <li class="menu-text">
                <span style="font: 400 2.0em/100% 'Satisfy', Helvetica, Sans-serif;">
                  <%= link_to "Mew Meets You", root_path %>
                </span>
              </li>
            </ul>
          </div>
          <div class="top-bar-right">
            <ul class="menu sign-up">
              <% if user_signed_in? %>
                <li>
                  <% if !current_user.avatar_url.nil? &&   !current_user.avatar_url.empty? %>
                    <img src="<%= current_user.avatar_url %>" />
                  <% else %>
                    <img src="http://rs732.pbsrc.com/albums/ww327/NinjaPie101/Missingno_Sprite1947934836-iaza.gif~c200" height="25" width="25"%>
                  <% end %>
                </li>
                <li>
                  <%= link_to current_user.username, user_path(current_user)%>
                </li>
                <li>
                  <%= link_to "Sign Out",
                    destroy_user_session_path, method: :delete, class:"button"
                  %>
                </li>
              <% else %>
                <li> <%= link_to "Sign In", new_user_session_path, class:"button" %> </li>
                <li> <%= link_to "Sign Up", new_user_registration_path, class:"button" %> </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<h1> Edit Your Profile </h1>

<div class="form-box">
  <%= form_for @user do |f| %>

    <%= f.label :email, "Email" %>
    <%= f.email_field :email, autofocus: true, :input_html => { :value => @user.email} %>

    <%= f.label :avatar_url, "Avatar" %>
    <%= f.text_field :avatar_url, :input_html => { :value => @user.avatar_url} %>

    <%= f.submit "Update Profile", :id=>"Update Profile" %>
  <% end %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<div class="row" id="gallery">
  <div class="columns small-3">
    <ul class="menu vertical">
      <%= link_to 'Edit Profile', edit_user_path(@user), class: "button" %>
      <%= link_to "Delete Account", user_registration_path, :method => :delete, class: "button"%>
      <li><strong><span style="font-size:200%">Profile Settings</span></strong></li>
      <li><strong>Email: </strong><%= @user.email %></li>
      <li><strong>Avatar:</strong></li>
      <li>
        <% if !@user.avatar_url.nil? && !@user.avatar_url.empty? %>
          <img src="<%= @user.avatar_url %>" />
        <% else %>
          <img src="http://rs732.pbsrc.com/albums/ww327/NinjaPie101/Missingno_Sprite1947934836-iaza.gif~c200" %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="columns small-9">
    <% i = 0 %>
    <% while i < @matches.length do %>
      <div class="row text-center">
        <% if @matches[i] %>
          <div class="small-12 large-4 columns">
            <div class="card">
              <div class="content">
                <div class="front">
                  <img src= '<%=@matches[i].image_url%>'/>
                </div>
                <div class='back'>
                  <p class='poke-p'><strong><%= @matches[i].name %></strong></p>
                  <p><span class='poke-h'>Weight:</span><span><class='poke-p'><%= @matches[i].weight %></p>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div style="height:1em;"></div>
        <% end %>
        <% if @matches[i+1] %>
          <div class="small-12 large-4 columns">
            <div class="card">
              <div class="content">
                <div class="front">
                  <img src='<%=@matches[i+1].image_url%>'/>
                </div>
                <div class='back'>
                  <p class='poke-p'><strong><%= @matches[i+1].name %></strong></p>
                  <p><span class='poke-h'>Weight:</span><span><class='poke-p'><%= @matches[i+1].weight %></p>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div style="height:1em"></div>
        <% end %>
        <% if @matches[i+2] %>
          <div class="small-12 large-4 columns">
            <div class="card">
              <div class="content">
                <div class="front">
                  <img src= '<%=@matches[i+2].image_url%>' width='200';
                    height='200';/>
                </div>
                <div class='back'>
                  <p class='poke-p'><strong><%= @matches[i+1].name %></strong></p>
                  <p><span class='poke-h'>Weight:</span><span><class='poke-p'><%= @matches[i+1].weight %></p>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div style="height:1em"></div>
        <% end %>
      </div>
      <% i += 3 %>
    <% end %>
  </div>
</div>